//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Providers.Api.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiManagerResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiManagerResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Providers.Api.Resx.ApiManagerResources", typeof(ApiManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoInternetAlert {
            get {
                return ResourceManager.GetString("NoInternetAlert", resourceCulture);
            }
        }
        
        internal static string CheckNetworkAlert {
            get {
                return ResourceManager.GetString("CheckNetworkAlert", resourceCulture);
            }
        }
        
        internal static string VerifyNetworkAlert {
            get {
                return ResourceManager.GetString("VerifyNetworkAlert", resourceCulture);
            }
        }
        
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string SessionExpiredAlert {
            get {
                return ResourceManager.GetString("SessionExpiredAlert", resourceCulture);
            }
        }
        
        internal static string SessionExpiredAlertMessage {
            get {
                return ResourceManager.GetString("SessionExpiredAlertMessage", resourceCulture);
            }
        }
        
        internal static string SomethingWrongAlert {
            get {
                return ResourceManager.GetString("SomethingWrongAlert", resourceCulture);
            }
        }
        
        internal static string OopsSomethingWrongAlert {
            get {
                return ResourceManager.GetString("OopsSomethingWrongAlert", resourceCulture);
            }
        }
        
        internal static string StillWorkingAlert {
            get {
                return ResourceManager.GetString("StillWorkingAlert", resourceCulture);
            }
        }
    }
}
